## Numpy assignment 

#### Write a function so that the columns of the output matrix are powers of the input vector. 
#### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

#### HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [2]:
import numpy as np

In [94]:
inp = [1,2,3,4,5,6]

In [95]:
def power_matrix(inp, number=None, decreasing = False):
    if number == None : 
        number = len(inp)
    if decreasing:
        matrix = [[element**power for power in range(number-1, -1, -1)] for element in inp]
        print(np.row_stack(matrix))
    else:
        matrix = [[element**power for power in range(0, number)] for element in inp]
        print(np.row_stack(matrix))
    

In [96]:
power_matrix(inp,4,decreasing=True)

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]]


#### Question: Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 

In [100]:
inp = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window_size = 3

In [101]:
def moving_average(inp,window_size):
    x = np.cumsum(inp, dtype=float)
    x[window_size:] = x[window_size:] - x[:-window_size]
    print(x[window_size - 1:] / window_size)

In [102]:
moving_average(inp,window_size)

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
